import type { LinkedInPost, PageContext } from './types'

export interface ExportConfig {
  downloadImages: boolean
  jsonFormat: 'single' | 'per-post'
  context: PageContext
  onImageProgress?: (current: number, total: number) => void
}

/* ── Helpers ── */

const getMediaType = (post: LinkedInPost): string => {
  if (post.hasVideo) return 'video'
  if (post.hasDocument) return 'document'
  if (post.hasPoll) return 'poll'
  if (post.hasArticle) return 'article'
  if (post.hasImage) return 'image'
  return 'text'
}

const escapeCSV = (value: string): string => {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

const formatDate = (isoDate: string | null): string => {
  if (!isoDate) return ''
  try {
    const d = new Date(isoDate)
    return d.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' })
  } catch {
    return isoDate
  }
}

const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType })
  downloadBlob(blob, filename)
}

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Extract activity ID from URN (e.g. "urn:li:activity:1234567890" → "1234567890")
 */
const getPostId = (post: LinkedInPost): string => {
  if (post.urn) {
    // Extract numeric ID from any URN format (activity:XXX, ugcPost:XXX, share:XXX, etc.)
    const match = post.urn.match(/:(\d+)$/)
    if (match) return match[1]
  }
  return `unknown-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
}

/**
 * Fetch a single image blob from LinkedIn CDN.
 */
const fetchImage = async (url: string): Promise<{ blob: Blob; ext: string } | null> => {
  try {
    const res = await fetch(url)
    if (!res.ok) return null
    const blob = await res.blob()
    const ct = res.headers.get('content-type') || 'image/jpeg'
    const ext = ct.includes('png')
      ? 'png'
      : ct.includes('gif')
        ? 'gif'
        : ct.includes('webp')
          ? 'webp'
          : 'jpg'
    return { blob, ext }
  } catch {
    return null
  }
}

/* ── README ── */

const generateReadme = (posts: LinkedInPost[], config: ExportConfig): string => {
  const date = new Date().toLocaleDateString('fr-FR', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
  const dates = posts
    .map((p) => p.parsedDate)
    .filter(Boolean)
    .sort() as string[]
  const from = dates[0] ? formatDate(dates[0]) : '—'
  const to = dates[dates.length - 1] ? formatDate(dates[dates.length - 1]) : '—'

  return `# LinkPull Export

- **Profile**: ${config.context.fullName} (${config.context.username})
- **Exported**: ${date}
- **Posts**: ${posts.length}
- **Period**: ${from} — ${to}
- **Version**: v0.1

## Files

- \`${config.jsonFormat === 'per-post' ? '{postId}.json' : 'posts.json'}\` — Post data with all metadata
- \`analytics.json\` — Aggregate statistics and averages
${config.downloadImages ? '- `media/{postId}/` — Downloaded post images\n' : ''}
---
*Generated by [LinkPull](https://github.com/magrinj/linkpull) — Privacy-first, no server*
`
}

/* ── Analytics ── */

const generateAnalytics = (posts: LinkedInPost[], config: ExportConfig): string => {
  const count = posts.length || 1
  const totalReactions = posts.reduce((s, p) => s + p.reactions, 0)
  const totalComments = posts.reduce((s, p) => s + p.comments, 0)
  const totalReposts = posts.reduce((s, p) => s + p.reposts, 0)
  const totalImpressions = posts.reduce((s, p) => s + (p.impressions || 0), 0)

  const mediaBreakdown: Record<string, number> = {
    text: 0,
    image: 0,
    video: 0,
    article: 0,
    document: 0,
    poll: 0,
  }
  for (const post of posts) {
    if (post.hasVideo) mediaBreakdown.video++
    else if (post.hasDocument) mediaBreakdown.document++
    else if (post.hasPoll) mediaBreakdown.poll++
    else if (post.hasArticle) mediaBreakdown.article++
    else if (post.hasImage) mediaBreakdown.image++
    else mediaBreakdown.text++
  }

  const dates = posts
    .map((p) => p.parsedDate)
    .filter(Boolean)
    .sort() as string[]

  return JSON.stringify(
    {
      profile: {
        username: config.context.username,
        fullName: config.context.fullName,
        profileUrl: config.context.profileUrl,
      },
      exportedAt: new Date().toISOString(),
      totalPosts: posts.length,
      dateRange: {
        from: dates[0] || null,
        to: dates[dates.length - 1] || null,
      },
      totals: {
        reactions: totalReactions,
        comments: totalComments,
        reposts: totalReposts,
        impressions: totalImpressions,
      },
      averages: {
        reactions: Math.round((totalReactions / count) * 10) / 10,
        comments: Math.round((totalComments / count) * 10) / 10,
        reposts: Math.round((totalReposts / count) * 10) / 10,
        impressions: Math.round((totalImpressions / count) * 10) / 10,
      },
      mediaBreakdown,
    },
    null,
    2,
  )
}

/* ── CSV (plain file) ── */

export const exportCSV = (posts: LinkedInPost[], filename: string): void => {
  const BOM = '\uFEFF'
  const headers = [
    'Date',
    'Texte',
    'Réactions',
    'Commentaires',
    'Reposts',
    'Impressions',
    'Type média',
    'Images',
    'URL',
  ]

  const rows = posts.map((post) =>
    [
      escapeCSV(formatDate(post.parsedDate)),
      escapeCSV(post.text),
      String(post.reactions),
      String(post.comments),
      String(post.reposts),
      post.impressions !== null ? String(post.impressions) : '',
      getMediaType(post),
      escapeCSV(post.images.join(' | ')),
      escapeCSV(post.postUrl || ''),
    ].join(','),
  )

  const csv = BOM + headers.join(',') + '\n' + rows.join('\n')
  downloadFile(csv, filename, 'text/csv;charset=utf-8')
}

/* ── JSON (plain file, no ZIP) ── */

export const exportJSONPlain = (posts: LinkedInPost[], filename: string): void => {
  const cleanPosts = posts.map(sanitizePost)
  const json = JSON.stringify(cleanPosts, null, 2)
  downloadFile(json, filename, 'application/json;charset=utf-8')
}

/**
 * Sanitize a post to ensure all values are JSON-safe primitives.
 * Protects against DOM elements or other non-serializable objects
 * surviving structured cloning from browser.storage.local.
 */
const sanitizePost = (post: LinkedInPost): LinkedInPost => ({
  urn: typeof post.urn === 'string' ? post.urn : null,
  postUrl: typeof post.postUrl === 'string' ? post.postUrl : null,
  authorName: String(post.authorName ?? ''),
  authorUrl: String(post.authorUrl ?? ''),
  timeLabel: String(post.timeLabel ?? ''),
  parsedDate: typeof post.parsedDate === 'string' ? post.parsedDate : null,
  text: String(post.text ?? ''),
  reactions: Number(post.reactions) || 0,
  comments: Number(post.comments) || 0,
  reposts: Number(post.reposts) || 0,
  impressions: post.impressions !== null ? Number(post.impressions) || 0 : null,
  images: Array.isArray(post.images)
    ? post.images.filter((v): v is string => typeof v === 'string')
    : [],
  hasImage: Boolean(post.hasImage),
  hasVideo: Boolean(post.hasVideo),
  hasDocument: Boolean(post.hasDocument),
  hasArticle: Boolean(post.hasArticle),
  hasPoll: Boolean(post.hasPoll),
})

/**
 * Safely serialize a post to JSON string.
 * Returns the JSON string on success, or an error JSON on failure.
 */
const safeStringifyPost = (post: LinkedInPost): string => {
  try {
    const clean = sanitizePost(post)
    return JSON.stringify(clean, null, 2)
  } catch (err) {
    return JSON.stringify(
      {
        error: err instanceof Error ? err.message : String(err),
        urn: String(post.urn ?? 'unknown'),
        postUrl: String(post.postUrl ?? ''),
      },
      null,
      2,
    )
  }
}

/* ── ZIP export (README + analytics + posts + optional images) ── */

export const exportZIP = async (
  posts: LinkedInPost[],
  filename: string,
  config: ExportConfig,
): Promise<void> => {
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()

  // Sanitize all posts upfront
  const cleanPosts = posts.map(sanitizePost)

  // README
  zip.file('README.md', generateReadme(cleanPosts, config))

  // Analytics
  zip.file('analytics.json', generateAnalytics(cleanPosts, config))

  // Posts
  if (config.jsonFormat === 'per-post') {
    for (const post of cleanPosts) {
      const id = getPostId(post)
      zip.file(`${id}.json`, safeStringifyPost(post))
    }
  } else {
    try {
      zip.file('posts.json', JSON.stringify(cleanPosts, null, 2))
    } catch {
      // Fallback: serialize each post individually, skip failures
      const safePosts = cleanPosts.map((p) => {
        try {
          JSON.stringify(p)
          return p
        } catch {
          return { ...p, text: '[serialization error]', images: [] }
        }
      })
      zip.file('posts.json', JSON.stringify(safePosts, null, 2))
    }
  }

  // Images
  if (config.downloadImages) {
    const imagePosts = cleanPosts.filter((p) => p.images.length > 0)
    const total = imagePosts.reduce((s, p) => s + p.images.length, 0)
    let downloaded = 0

    for (const post of imagePosts) {
      const id = getPostId(post)
      for (let i = 0; i < post.images.length; i++) {
        const result = await fetchImage(post.images[i])
        if (result) {
          const imgName =
            post.images.length === 1 ? `image.${result.ext}` : `image-${i + 1}.${result.ext}`
          zip.file(`media/${id}/${imgName}`, result.blob)
        }
        downloaded++
        config.onImageProgress?.(downloaded, total)
      }
    }
  }

  const blob = await zip.generateAsync({ type: 'blob' })
  downloadBlob(blob, filename)
}

/* ── Clipboard ── */

export const copyToClipboard = async (posts: LinkedInPost[]): Promise<void> => {
  const lines = posts.map((post) => {
    const parts: string[] = []
    parts.push(`${formatDate(post.parsedDate)}`)

    const stats: string[] = []
    if (post.reactions > 0) stats.push(`${post.reactions} reactions`)
    if (post.comments > 0) stats.push(`${post.comments} comments`)
    if (post.impressions !== null && post.impressions > 0)
      stats.push(`${post.impressions} impressions`)
    if (stats.length > 0) parts.push(stats.join(' \u00B7 '))

    const preview = post.text.length > 200 ? post.text.slice(0, 200) + '...' : post.text
    if (preview) parts.push(preview)

    if (post.postUrl) parts.push(post.postUrl)

    return parts.join('\n')
  })

  await navigator.clipboard.writeText(lines.join('\n---\n'))
}
